result:
  image:
    repository: codedev.jfrog.io/poc-demo-1-docker-local/result
    tag: pr-132-result-breaking-change-67105be
vote:
  image:
    repository: codedev.jfrog.io/poc-demo-1-docker-local/vote
    tag: pr-86-random-vote-change-28-7a550fd
worker:
  image:
    repository: codedev.jfrog.io/poc-demo-1-docker-local/worker
    tag: stable
