# Default values for worker.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: codedev.jfrog.io/poc-demo-1-docker-local/worker
  tag: stable
redis:
  usePassword: false
replicaCount: 1
